DROP TABLE IF EXISTS `User`;
CREATE TABLE User (
name VARCHAR(255) NOT NULL UNIQUE,
id bigint(20) NOT NULL AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
password VARCHAR(64) NOT NULL,
PRIMARY KEY(id)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `Patient`;
CREATE TABLE Patient (
patientId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
id MEDIUMINT UNSIGNED,
patientDiseaseName VARCHAR(255) NOT NULL,
PRIMARY KEY(patientId),
FOREIGN KEY(id) REFERENCES User(id)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `Doctor`;
CREATE TABLE Doctor (
doctorId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
id MEDIUMINT UNSIGNED,
patientId MEDIUMINT UNSIGNED,
PRIMARY KEY(doctorId),
FOREIGN KEY(id) REFERENCES User(id),
FOREIGN KEY(patientId) REFERENCES Patient(patientId)
) DEFAULT CHARSET=utf8;

-- DROP TABLE IF EXISTS `DoctorToPatientInfo`;
-- CREATE TABLE DoctorToPatientInfo (
-- doctorId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
-- id MEDIUMINT NOT NULL UNSIGNED,
-- PRIMARY KEY(doctorId),
-- FOREIGN KEY(id) REFERENCES User(id));