DROP TABLE IF EXISTS `User`;
CREATE TABLE User (
userName VARCHAR(255) NOT NULL UNIQUE,
userId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
userEmail VARCHAR(100) NOT NULL,
userPassword VARCHAR(64) NOT NULL,
PRIMARY KEY(userId)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `Patient`;
CREATE TABLE Patient (
patientId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
userId MEDIUMINT UNSIGNED,
patientDiseaseName VARCHAR(255) NOT NULL,
PRIMARY KEY(patientId),
FOREIGN KEY(userId) REFERENCES User(userId)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `Doctor`;
CREATE TABLE Doctor (
doctorId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
userId MEDIUMINT UNSIGNED,
patientId MEDIUMINT UNSIGNED,
PRIMARY KEY(doctorId),
FOREIGN KEY(userId) REFERENCES User(userId),
FOREIGN KEY(patientId) REFERENCES Patient(patientId)
) DEFAULT CHARSET=utf8;

-- DROP TABLE IF EXISTS `DoctorToPatientInfo`;
-- CREATE TABLE DoctorToPatientInfo (
-- doctorId MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
-- userId MEDIUMINT NOT NULL UNSIGNED,
-- PRIMARY KEY(doctorId),
-- FOREIGN KEY(userId) REFERENCES User(userId));